### ISSUE TITLE
Unexpected keyword argument.

### ISSUE THREAD

**Issue by alexeyignatiev** [mvcisback/py-aiger#113]
Hi @mvcisback. This is a problem I get with the most recent version:

```
aign@antares:~$ python -c 'import aiger'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/aiger/__init__.py", line 6, in <module>
    from aiger.expr import atom, atoms, ite, BoolExpr
  File "/usr/local/lib/python3.7/site-packages/aiger/expr.py", line 9, in <module>
    @attr.s(frozen=True, slots=True, eq=False, auto_attribs=True, hash=True)
TypeError: attrs() got an unexpected keyword argument 'eq'
```

**Comment by mvcisback** [comment]
@alexeyignatiev Thanks for pointing this out. The problem is that the `attr` library recently deprecated the `cmp` keyword and introduced the `eq` keyword to use instead. 

In preparation for the deprecation, I changed `aiger` but I did not update the dependency to reflect.

The latest version on `pypi` (`py-aiger`== 3.4.1)  now requires `attr==19.3`.
